language:
  - ruby
sudo: false
rvm:
  - 2.3.0
env:
  - INTEGRATION_TEST=false
  - INTEGRATION_TEST=true
matrix:
  fast_finish: true
  allow_failures:
    - env: INTEGRATION_TEST=true
cache:
  bundler: true
  directories:
    - ~/.rvm/gems
before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DATABASE_URL=postgres://postgres@localhost/database
install:
  - travis_retry bin/setup
script: bin/rspec
services:
  - postgresql
  - redis-server
